### PR TITLE
Restructure as a python package

### PR DESCRIPTION
**Pull request by dpryan79**
This PR restructures lace as a standard python package, which (A) makes the newest version actually work (as is it can't be used unless your working directory is in the source code) and (B) makes maintenance easier on bioconda. I've taken the liberty of bumping the version to 1.14.0.

### CODE REVIEW

**Comment by dpryan79** [comment]
This closes #48, see also https://github.com/bioconda/bioconda-recipes/pull/15934

**Comment by druvus** [comment]
I am also interested to see this merged. Lace would be much easier to use if it properly packaged.

**Comment by nadiadavidson** [comment]
Sorry didn't see this pull request until now. Thanks!

**Comment by dpryan79** [comment]
Thanks @nadiadavidson, if you could tag a release on github too that'd be awesome!

**Comment by nadiadavidson** [comment]
Done. Thanks for your contribution.

**Pull request merged**
